[package]
name = "wildcard"
version = "0.1.0"
edition.workspace = true
repository.workspace = true
license.workspace = true

[dependencies]
memchr.workspace = true

[dev-dependencies]
rstest.workspace = true
