# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "04:00"
    labels:
      - "dependencies"
      - "github-actions"
    commit-message:
      prefix: "build"
      include: "scope"
  - package-ecosystem: "cargo"
    directory: "/"
    schedule:
      interval: daily
      time: "18:00"
      timezone: "Etc/UTC"
    open-pull-requests-limit: 0
    labels:
      - "dependencies"
      - "rust"
      - "security"
    commit-message:
      prefix: "build"
      include: "scope"
  - package-ecosystem: "cargo"
    directory: "/"
    schedule:
      interval: weekly
      day: friday
      time: "18:00"
      timezone: "Etc/UTC"
    allow:
      - dependency-type: direct
    labels:
      - "dependencies"
      - "rust"
    commit-message:
      prefix: "build"
      include: "scope"
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-patch"]
      - dependency-name: "anstream"
        update-types: ["version-update:semver-minor"]
      - dependency-name: "anyhow"
        update-types: ["version-update:semver-minor"]
      - dependency-name: "assert_matches"
        update-types: ["version-update:semver-minor"]
      - dependency-name: "clap"
        update-types: ["version-update:semver-minor"]
      - dependency-name: "clap_complete"
        update-types: ["version-update:semver-minor"]
      - dependency-name: "const-str"
        update-types: ["version-update:semver-minor"]
      - dependency-name: "derive_more"
        update-types: ["version-update:semver-minor"]
      - dependency-name: "dirs"
        update-types: ["version-update:semver-minor"]
      - dependency-name: "enum-map"
        update-types: ["version-update:semver-minor"]
      - dependency-name: "enumset"
        update-types: ["version-update:semver-minor"]
      - dependency-name: "flate2"
        update-types: ["version-update:semver-minor"]
      - dependency-name: "fnv"
        update-types: ["version-update:semver-minor"]
      - dependency-name: "humantime"
        update-types: ["version-update:semver-minor"]
      - dependency-name: "itoa"
        update-types: ["version-update:semver-minor"]
      - dependency-name: "known-folders"
        update-types: ["version-update:semver-minor"]
      - dependency-name: "kqueue"
        update-types: ["version-update:semver-minor"]
      - dependency-name: "maplit"
        update-types: ["version-update:semver-minor"]
      - dependency-name: "memchr"
        update-types: ["version-update:semver-minor"]
      - dependency-name: "notify"
        update-types: ["version-update:semver-minor"]
      - dependency-name: "num_cpus"
        update-types: ["version-update:semver-minor"]
      - dependency-name: "once_cell"
        update-types: ["version-update:semver-minor"]
      - dependency-name: "owo-colors"
        update-types: ["version-update:semver-minor"]
      - dependency-name: "pest"
        update-types: ["version-update:semver-minor"]
      - dependency-name: "pest_derive"
        update-types: ["version-update:semver-minor"]
      - dependency-name: "regex"
        update-types: ["version-update:semver-minor"]
      - dependency-name: "rust-embed"
        update-types: ["version-update:semver-minor"]
      - dependency-name: "semver"
        update-types: ["version-update:semver-minor"]
      - dependency-name: "serde"
        update-types: ["version-update:semver-minor"]
      - dependency-name: "serde_json"
        update-types: ["version-update:semver-minor"]
      - dependency-name: "serde_plain"
        update-types: ["version-update:semver-minor"]
      - dependency-name: "shellwords"
        update-types: ["version-update:semver-minor"]
      - dependency-name: "snap"
        update-types: ["version-update:semver-minor"]
      - dependency-name: "static_assertions"
        update-types: ["version-update:semver-minor"]
      - dependency-name: "thiserror"
        update-types: ["version-update:semver-minor"]
      - dependency-name: "titlecase"
        update-types: ["version-update:semver-minor"]
      - dependency-name: "toml"
        update-types: ["version-update:semver-minor"]
      - dependency-name: "unicode-segmentation"
        update-types: ["version-update:semver-minor"]
      - dependency-name: "ureq"
        update-types: ["version-update:semver-minor"]
      - dependency-name: "utf8-supported"
        update-types: ["version-update:semver-minor"]
      - dependency-name: "wild"
        update-types: ["version-update:semver-minor"]
      - dependency-name: "wildmatch"
        update-types: ["version-update:semver-minor"]
      - dependency-name: "yaml-peg"
        update-types: ["version-update:semver-minor"]
