#:schema https://raw.githubusercontent.com/pamburus/hl/42eb24f79f492b02278057e5d7f3cb3bb2e89b9e/schema/json/theme.schema.v1.json

version = "1.0"
tags = ["overlay", "dark", "light", "16color"]

# Styles define general purpose styles used throughout the theme.
[styles.accent]
modes = ["italic"]
