#:schema https://raw.githubusercontent.com/pamburus/hl/v0.35.0/schema/json/theme.schema.v1.json

version = "1.1"
tags = ["overlay", "dark", "light", "16color"]

# Styles define general purpose styles used throughout the theme.
[styles.accent]
modes = ["italic"]
