#:schema https://raw.githubusercontent.com/pamburus/hl/277cc7bf68f58bcfb7a98f4ab4887f809d81caef/schema/json/theme.schema.v1.json

version = "1.0"
tags = ["overlay"]

# Styles define general purpose styles used throughout the theme.
[styles.accent]
modes = ["italic"]
