#:schema ../../../schema/json/theme.schema.v1.json

version = "1.0"

# Styles define general purpose styles used throughout the theme.
[styles]
default = {  }
primary = {  }
secondary = { style = "primary", modes = ["faint"] }
emphasized = { style = "primary", modes = ["bold"] }
muted = { style = "secondary" }
accent = { style = "secondary" }
accent-secondary = { style = "secondary" }
syntax = { style = "emphasized" }
info = { foreground = "cyan" }
warning = { foreground = "yellow" }
error = { foreground = "bright-red" }

# Elements define specific styles for different log elements.
[elements]
input-number = { style = "muted" }
input-number-inner = { style = "secondary" }
input-name = { style = "muted" }
input-name-inner = { style = "secondary" }
time = { style = "secondary" }
level = { style = "muted" }
level-inner = { style = "primary" }
logger = { style = "accent-secondary" }
caller = { style = "secondary", modes = ["italic"] }
message = { style = "emphasized" }
message-delimiter = { style = "muted" }
field = { style = "muted" }
key = { style = "accent" }
ellipsis = { style = "muted" }
object = { style = "syntax" }
array = { style = "syntax" }
string = { style = "primary" }
number = { style = "primary" }
boolean = { style = "primary" }
null = { style = "primary" }

# Levels define styles for different log levels.
[levels]
trace = { level-inner = { style = "secondary" } }
debug = { level-inner = { style = "secondary" } }
info = { level-inner = { style = "info" } }
warning = { level-inner = { style = "warning" }, message = { style = "warning" } }
error = { level-inner = { style = "error" }, message = { style = "error" } }

# Indicators define styles for various status indicators.
[indicators]
[indicators.sync]
synced = { text = " " }
failed = { text = "!", inner.style = { style = "warning", modes = ["bold"] } }
