#:schema https://raw.githubusercontent.com/pamburus/hl/29ced163a1c66b7cc94b03665b7306f51104690c/schema/json/theme.schema.v1.json

version = "1.0"

# Styles define general purpose styles used throughout the theme.
[styles]
default = {  }
primary = { modes = ["-faint"] }
secondary = { style = "primary", modes = ["faint"] }
strong = { style = "primary", modes = ["bold"] }
muted = { style = "secondary" }
accent = { style = "secondary" }
accent-secondary = { style = ["accent", "secondary"] }
message = { style = "strong" }
syntax = { style = "strong" }
status = { modes = ["-faint"] }
level = { style = "status" }
trace = { style = "secondary" }
debug = { foreground = "magenta" }
info = { foreground = "cyan" }
warning = { foreground = "yellow" }
error = { foreground = "bright-red" }

# Elements define specific styles for different log elements.
[elements]
input = { style = "secondary" }
time = { style = "secondary" }
level = { style = "muted" }
level-inner = { style = "level" }
logger = { style = "accent-secondary" }
caller = { style = "secondary", modes = ["italic"] }
message = { style = "message" }
message-delimiter = { style = "muted" }
field = { style = "muted" }
key = { style = "accent" }
ellipsis = { style = "muted" }
object = { style = "syntax" }
array = { style = "syntax" }
string = { style = "primary" }
number = { style = "primary" }
boolean = { style = "primary" }
null = { style = "primary" }

# Levels define styles for different log levels.
[levels]
trace = { level-inner = { style = ["level", "trace"] } }
debug = { level-inner = { style = ["level", "debug"] } }
info = { level-inner = { style = ["level", "info"] } }
warning = { level-inner = { style = ["level", "warning"] }, message = { style = ["message", "warning"] } }
error = { level-inner = { style = ["level", "error"] }, message = { style = ["message", "error"] } }

# Indicators define styles for various status indicators.
[indicators]
[indicators.sync]
synced = { text = " " }
failed = { text = "!", inner.style = { style = ["status", "warning"], modes = ["bold"] } }
