#:schema ../../../schema/json/theme.schema.v1.json

version = "1.0"
tags = [
  "dark",
  "truecolor",
]

#
# Styles define general purpose styles used throughout the theme.
#
[styles]
[styles.primary]
foreground = "#bfbdb6"

[styles.secondary]
foreground = "#565b66"

[styles.emphasized]
foreground = "#95e6cb"

[styles.warning]
foreground = "#e6b450"

[styles.error]
foreground = "#d95757"

[styles.accent]
foreground = "#73b8ff"

[styles.accent-secondary]
foreground = "#3f5d7f"

[styles.syntax]
modes = [
  "bold",
]

#
# Elements define specific styles for different log elements.
#
[elements]
[elements.logger]
style = "accent-secondary"

[elements.level]
style = "accent-secondary"

[elements.field]
style = "accent-secondary"

[elements.number]
foreground = "#7fd962"

[elements.boolean]
foreground = "#e6b450"

[elements.null]
foreground = "#d95757"

#
# Levels define styles for different log levels.
#
[levels]
[levels.debug.level-inner]
foreground = "#d2a6ff"

[levels.info.level-inner]
foreground = "#39bae6"
