#:schema https://raw.githubusercontent.com/pamburus/hl/42eb24f79f492b02278057e5d7f3cb3bb2e89b9e/schema/json/theme.schema.v1.json

version = "1.0"
tags = ["dark", "truecolor"]

#
# Styles define general purpose styles used throughout the theme.
#
[styles]
[styles.primary]
foreground = "#bfbdb6"

[styles.secondary]
modes = ["-faint"]
foreground = "#565b66"

[styles.strong]
modes = ["-bold"]
foreground = "#95e6cb"

[styles.accent]
foreground = "#73b8ff"

[styles.accent-secondary]
foreground = "#3f5d7f"

[styles.syntax]
modes = ["bold"]
foreground = "default"

[styles.debug]
foreground = "#d2a6ff"

[styles.warning]
foreground = "#e6b450"

[styles.error]
foreground = "#d95757"

[styles.info]
foreground = "#39bae6"

#
# Elements define specific styles for different log elements.
#
[elements]
[elements.level]
style = "accent-secondary"
modes = ["-italic"]

[elements.field]
style = "accent-secondary"

[elements.number]
foreground = "#7fd962"

[elements.boolean]
foreground = "#e6b450"

[elements.null]
foreground = "#d95757"

#
# Levels define styles for different log levels.
#
[levels]
[levels.warning.message]
style = ["message", "warning"]

[levels.error.message]
style = ["message", "error"]
