#:schema https://raw.githubusercontent.com/pamburus/hl/ba6c2609f603441946d90aa92b7aeec6422f561f/schema/json/theme.schema.v1.json

version = 1
tags = [
  "light",
  "truecolor",
]

#
# Styles define general purpose styles used throughout the theme.
#
[styles]
[styles.primary]
foreground = "#5c6166"

[styles.secondary]
foreground = "#a7aaad"

[styles.emphasized]
style = "primary"

[styles.info]
foreground = "#55b4d4"

[styles.warning]
foreground = "#ffaa33"

[styles.error]
foreground = "#e65050"

[styles.accent]
foreground = "#478acc"

[styles.accent-secondary]
foreground = "#8a9199"

[styles.syntax]
modes = [
  "bold",
]

#
# Elements define specific styles for different log elements.
#
[elements]
[elements.level]
foreground = "#a8caf1"

[elements.field]
style = "accent"

[elements.string]
foreground = "#5c6166"

[elements.number]
foreground = "#6cbf43"

[elements.boolean]
foreground = "#86b300"

[elements.null]
foreground = "#ed9366"

#
# Levels define styles for different log levels.
#
[levels]
[levels.debug.level-inner]
foreground = "#a37acc"

[levels.error.message]
foreground = "#ff7383"
