#:schema https://raw.githubusercontent.com/pamburus/hl/c5f7bbb768219023877d4d65959972d0f9701d5e/schema/json/theme.schema.v0.json

tags = ["light", "16color"]

[elements.input]
foreground = "bright-black"

[elements.time]
foreground = "bright-black"

[elements.logger]
foreground = "bright-black"

[elements.caller]
foreground = "bright-black"

[elements.level]
foreground = "default"

[elements.message]
foreground = "black"

[elements.message-delimiter]
foreground = "bright-black"

[elements.field]
foreground = "bright-black"

[elements.key]
foreground = "green"

[elements.ellipsis]
foreground = "bright-black"

[elements.object]
foreground = "default"

[elements.array]
foreground = "default"

[elements.string]
foreground = "default"

[elements.number]
foreground = "cyan"

[elements.boolean]
foreground = "yellow"

[elements.null]
foreground = "yellow"

[levels.trace.level-inner]
foreground = "bright-black"

[levels.debug.level-inner]
foreground = "magenta"

[levels.info.level-inner]
foreground = "cyan"

[levels.warning.level]
foreground = "bright-yellow"
modes = ["reverse"]

[levels.error.level]
foreground = "bright-red"
modes = ["reverse"]
