#:schema https://raw.githubusercontent.com/pamburus/hl/e6cc1ea34263c5b208f6582c0a4e231379da0fe9/schema/json/theme.schema.v1.json

version = "1.0"
tags = ["dark", "256color"]

#
# Styles define general purpose styles used throughout the theme.
#
[styles]
[styles.primary]
foreground = 36

[styles.secondary]
foreground = 8

[styles.emphasized]
foreground = 174

[styles.message]

[styles.accent]
foreground = 117

[styles.accent-secondary]
style = "secondary"

[styles.debug]
foreground = 31

[styles.info]
foreground = 68

[styles.warning]
foreground = 214

[styles.error]
foreground = 202

#
# Elements define specific styles for different log elements.
#
[elements]
[elements.input]
foreground = "bright-black"

[elements.level]
foreground = 139

[elements.field]
foreground = 60

[elements.key]
style = "accent"
modes = ["underline"]

[elements.number]
foreground = 41

[elements.boolean]
foreground = 192

[elements.null]
foreground = 136

#
# Levels define styles for different log levels.
#
[levels]
[levels.warning.time]
style = "warning"

[levels.warning.message]
foreground = "yellow"

[levels.error.time]
style = "error"

[levels.error.message]
foreground = "bright-red"
