#:schema https://raw.githubusercontent.com/pamburus/hl/e6cc1ea34263c5b208f6582c0a4e231379da0fe9/schema/json/theme.schema.v1.json

version = "1.0"
tags = ["dark", "light", "16color"]

#
# Styles define general purpose styles used throughout the theme.
#
[styles]
[styles.primary]
style = "default"

[styles.secondary]
foreground = "cyan"
modes = ["faint"]

[styles.strong]
style = "default"

[styles.syntax]
modes = ["bold"]

[styles.accent]
foreground = "cyan"

[styles.debug]
foreground = "magenta"

[styles.info]
foreground = "cyan"

[styles.warning]
foreground = "yellow"

[styles.error]
foreground = "bright-red"

#
# Elements define specific styles for different log elements.
#
[elements]
[elements.number]
foreground = "bright-blue"

[elements.boolean]
foreground = "yellow"

[elements.boolean-false]
foreground = "red"

[elements.null]
foreground = "red"
