#:schema https://raw.githubusercontent.com/pamburus/hl/29ced163a1c66b7cc94b03665b7306f51104690c/schema/json/theme.schema.v1.json

version = "1.0"
tags = ["dark", "256color"]

#
# Styles define general purpose styles used throughout the theme.
#
[styles]
[styles.primary]
foreground = 116

[styles.secondary]
foreground = 30

[styles.strong]
foreground = 195

[styles.accent]
foreground = 111

[styles.syntax]
foreground = 255
modes = ["bold"]

[styles.debug]
foreground = 170

[styles.info]
foreground = 146

[styles.warning]
foreground = 215

[styles.error]
foreground = 210

#
# Elements define specific styles for different log elements.
#
[elements]
[elements.level]
style = "muted"
modes = ["faint"]

[elements.level-inner]
style = "primary"
modes = ["-faint"]

[elements.number]
foreground = 42

[elements.boolean-true]
foreground = 41

[elements.boolean-false]
foreground = 210

[elements.null]
foreground = 210
