#:schema ../../../schema/json/theme.schema.v1.json

version = "1.1"
tags = ["dark", "light", "16color"]

#
# Styles define general purpose styles used throughout the theme.
#
[styles]
[styles.debug]
foreground = "default"

[styles.info]
foreground = "green"

[styles.warning]
foreground = "bright-yellow"

[styles.error]
foreground = "bright-red"

#
# Elements define specific styles for different log elements.
#
[elements]
[elements.null]
foreground = "bright-red"

#
# Levels define styles for different log levels.
#
[levels]
[levels.warning]
message.style = ["message", "warning"]
message.foreground = "yellow"

[levels.error]
message.style = ["message", "error"]
