#:schema ../../../schema/json/theme.schema.v1.json

version = "1.0"
tags = ["dark", "light", "16color"]

[elements.null]
style = "primary"
foreground = "bright-red"

[levels.trace.level-inner]
modes = ["faint"]

[levels.debug.level-inner]
foreground = "default"

[levels.info.level-inner]
foreground = "green"

[levels.warning.level-inner]
foreground = "bright-yellow"

[levels.warning.message]
foreground = "yellow"

[levels.error.level-inner]
foreground = "bright-red"

[levels.error.message]
foreground = "bright-red"
