#:schema https://raw.githubusercontent.com/pamburus/hl/2b8b974f9a23006987a23e0d1948849c2da4c378/schema/json/theme.schema.json

version = 1
tags = ["dark", "light", "16color"]

[elements.null]
style = "primary"
foreground = "bright-red"

[levels.trace.level-inner]
modes = ["faint"]

[levels.debug.level-inner]
foreground = "default"

[levels.info.level-inner]
foreground = "green"

[levels.warning.level-inner]
foreground = "bright-yellow"

[levels.warning.message]
foreground = "yellow"

[levels.error.level-inner]
foreground = "bright-red"

[levels.error.message]
foreground = "bright-red"
