#:schema https://raw.githubusercontent.com/pamburus/hl/v0.35.4/schema/json/theme.schema.v1.json

version = "1.1"
tags = ["dark", "truecolor"]

#
# Styles define general purpose styles used throughout the theme.
#
[styles]
[styles.primary]
foreground = "#56b6c2"

[styles.secondary]
modes = ["-faint"]
foreground = "#426d77"

[styles.muted]
foreground = "#666b76"

[styles.strong]
modes = ["-bold"]
foreground = "#abb2bf"

[styles.accent]
foreground = "#61afef"

[styles.accent-secondary]
style = "secondary"
foreground = "#476a8c"

[styles.syntax]
modes = ["bold"]
foreground = "default"

[styles.trace]
foreground = "#666b76"

[styles.debug]
foreground = "#c678dd"

[styles.info]
foreground = "#56b6c2"

[styles.warning]
foreground = "#e5c07b"

[styles.error]
foreground = "#e06c75"

#
# Elements define specific styles for different log elements.
#
[elements]
[elements.field]
style = "accent-secondary"

[elements.level]
style = "accent-secondary"

[elements.number]
foreground = "#98c379"

[elements.boolean]
foreground = "#e5c07b"

[elements.null]
foreground = "#e06c75"

#
# Levels define styles for different log levels.
#
[levels]
[levels.warning]
message.style = ["message", "warning"]

[levels.error]
message.style = ["message", "error"]

#
# Indicators define styles for various status indicators.
#
[indicators.sync.failed.inner.style]
foreground = "#e5c07b"
modes = ["bold"]
