#:schema https://raw.githubusercontent.com/pamburus/hl/29ced163a1c66b7cc94b03665b7306f51104690c/schema/json/theme.schema.v1.json

version = "1.0"
tags = ["light", "truecolor"]

#
# Styles define general purpose styles used throughout the theme.
#
[styles]
[styles.primary]
foreground = "#383a42"

[styles.secondary]
foreground = "#a0a1a7"

[styles.message]
style = "primary"

[styles.syntax]
modes = ["bold"]

[styles.accent]
foreground = "#4078f2"

[styles.accent-secondary]
foreground = "#0184bc"

[styles.debug]
foreground = "#a626a4"

[styles.info]
foreground = "#0184bc"

[styles.warning]
foreground = "#c18401"

[styles.error]
foreground = "#e45649"

#
# Elements define specific styles for different log elements.
#
[elements]
[elements.number]
foreground = "#50a14f"

[elements.boolean]
foreground = "#986801"

[elements.null]
foreground = "#e45649"

#
# Indicators define styles for various status indicators.
#
[indicators]
[indicators.sync]
synced = { text = " " }
failed = { text = "!", inner.style = { foreground = "#c18401", modes = ["bold"] } }
