#:schema https://raw.githubusercontent.com/pamburus/hl/v0.36.0/schema/json/theme.schema.v1.json

version = "1.1"
tags = ["dark", "truecolor"]

#
# Styles define general purpose styles used throughout the theme.
#
[styles]
[styles.primary]
foreground = "#abb2bf"

[styles.secondary]
modes = ["-faint"]
foreground = "#636d83"

[styles.strong]
modes = ["bold"]
foreground = "#cfd7e5"

[styles.accent]
foreground = "#61afef"

[styles.debug]
foreground = "#c678dd"

[styles.info]
foreground = "#56b6c2"

[styles.warning]
foreground = "#d19a66"

[styles.error]
foreground = "#e06c75"

#
# Elements define specific styles for different log elements.
#
[elements]
[elements.number]
foreground = "#98c379"

[elements.boolean]
foreground = "#d19a66"

[elements.null]
style = "error"

#
# Levels define styles for different log levels.
#
[levels]
[levels.warning.level]
style = ["level", "warning"]
modes = ["reverse"]

[levels.error.time]
style = "error"

[levels.error.level]
style = ["level", "error"]
modes = ["reverse"]

#
# Indicators define styles for various status indicators.
#
[indicators.sync.failed.inner.style]
foreground = "#d19a66"
modes = ["bold"]
