#:schema https://raw.githubusercontent.com/pamburus/hl/c5f7bbb768219023877d4d65959972d0f9701d5e/schema/json/theme.schema.v0.json

tags = [
  "dark",
  "truecolor",
]
"$palette" = [
  "#abb2bf",
  "#cfd7e5",
  "#e06c75",
  "#636d83",
  "#61afef",
  "#f4a460",
  "#56b6c2",
  "#c678dd",
  "#98c379",
]

[elements.input]
foreground = "#636d83"

[elements.time]
foreground = "#636d83"

[elements.logger]
foreground = "#636d83"

[elements.caller]
foreground = "#636d83"
modes = [
  "italic",
]

[elements.level]
foreground = "#636d83"

[elements.message]
foreground = "#cfd7e5"

[elements.message-delimiter]
foreground = "#636d83"

[elements.field]
foreground = "#636d83"

[elements.key]
foreground = "#61afef"

[elements.ellipsis]
foreground = "#636d83"

[elements.object]
foreground = "#cfd7e5"
modes = [
  "bold",
]

[elements.array]
foreground = "#cfd7e5"
modes = [
  "bold",
]

[elements.string]
foreground = "#abb2bf"

[elements.number]
foreground = "#98c379"

[elements.boolean]
foreground = "#f4a460"

[elements.null]
foreground = "#e06c75"

[levels.trace.level-inner]
foreground = "#636d83"

[levels.debug.level-inner]
foreground = "#c678dd"

[levels.info.level-inner]
foreground = "#56b6c2"

[levels.warning.level-inner]
foreground = "#f4a460"

[levels.warning.message]
foreground = "#f4a460"

[levels.error.level-inner]
foreground = "#e06c75"

[levels.error.message]
foreground = "#e06c75"

[indicators.sync.synced]
text = " "

[indicators.sync.failed]
text = "!"

[indicators.sync.failed.inner.style]
foreground = "#f4a460"
modes = [
  "bold",
]
