#:schema https://raw.githubusercontent.com/pamburus/hl/e6cc1ea34263c5b208f6582c0a4e231379da0fe9/schema/json/theme.schema.v1.json

version = "1.0"
tags = ["dark", "light", "16color"]

#
# Styles define general purpose styles used throughout the theme.
#
[styles]
[styles.accent]
foreground = "bright-blue"

[styles.accent-secondary]
style = "secondary"

[styles.trace]
foreground = "bright-black"

[styles.debug]
foreground = "bright-magenta"

[styles.info]
foreground = "cyan"

[styles.warning]
foreground = "yellow"

[styles.error]
foreground = "bright-red"

#
# Elements define specific styles for different log elements.
#
[elements]
[elements.level]
modes = ["faint"]

[elements.level-inner]
modes = ["bold"]

[elements.number]
foreground = "green"

[elements.boolean-true]
foreground = "yellow"

[elements.boolean-false]
foreground = "red"

[elements.null]
foreground = "bright-red"
