#:schema https://raw.githubusercontent.com/pamburus/hl/677a02dbe9b11112f2dec967e61392b1c78ba03a/schema/json/theme.schema.json

tags = [
  "dark",
  "light",
  "16color",
]

[elements.input]
modes = [
  "faint",
]

[elements.time]
modes = [
  "faint",
]

[elements.logger]
modes = [
  "faint",
]

[elements.caller]
modes = [
  "faint",
  "italic",
]

[elements.level]
foreground = "default"
modes = [
  "faint",
]

[elements.message]
foreground = "default"
modes = [
  "bold",
]

[elements.message-delimiter]
modes = [
  "faint",
]

[elements.field]
modes = [
  "faint",
]

[elements.key]
foreground = "bright-blue"

[elements.ellipsis]
modes = [
  "faint",
]

[elements.object]
modes = [
  "bold",
]

[elements.array]
modes = [
  "bold",
]

[elements.string]
foreground = "default"

[elements.number]
foreground = "green"

[elements.boolean]
foreground = "yellow"

[elements.boolean-false]
foreground = "red"

[elements.null]
foreground = "bright-red"

[levels.trace.level-inner]
foreground = "bright-black"
modes = [
  "bold",
]

[levels.debug.level-inner]
foreground = "bright-magenta"
modes = [
  "bold",
]

[levels.info.level-inner]
foreground = "cyan"
modes = [
  "bold",
]

[levels.warning.message]
foreground = "yellow"
modes = [
  "bold",
]

[levels.warning.level-inner]
foreground = "yellow"
modes = [
  "bold",
]

[levels.error.message]
foreground = "bright-red"
modes = [
  "bold",
]

[levels.error.level-inner]
foreground = "bright-red"
modes = [
  "bold",
]

[indicators.sync.synced]
text = " "

[indicators.sync.failed]
text = "!"

[indicators.sync.failed.inner.style]
foreground = "yellow"
modes = [
  "bold",
]
