#:schema https://raw.githubusercontent.com/pamburus/hl/v0.35.2/schema/json/theme.schema.v1.json

version = "1.1"
tags = ["dark", "light", "16color"]

#
# Styles define general purpose styles used throughout the theme.
#
[styles]
[styles.accent]
modes = ["-faint"]
foreground = "bright-blue"

[styles.trace]
style = "default"
foreground = "bright-black"

[styles.debug]
foreground = "bright-magenta"

[styles.info]
foreground = "cyan"

[styles.warning]
foreground = "yellow"

[styles.error]
foreground = "bright-red"

#
# Elements define specific styles for different log elements.
#
[elements]
[elements.level]
modes = ["faint"]

[elements.level-inner]
modes = ["-faint", "bold"]

[elements.logger]
style = ["accent", "secondary"]
foreground = "default"

[elements.number]
foreground = "green"

[elements.boolean-true]
foreground = "yellow"

[elements.boolean-false]
foreground = "red"

[elements.null]
foreground = "bright-red"

#
# Levels define styles for different log levels.
#
[levels]
[levels.warning]
message.style = ["message", "warning"]

[levels.error]
message.style = ["message", "error"]
