#:schema https://raw.githubusercontent.com/pamburus/hl/f2d142049de7704b555a67e5e06289de64b91551/schema/json/theme.schema.v1.json

version = "1.0"
tags = ["dark", "light", "16color"]

#
# Styles define general purpose styles used throughout the theme.
#
[styles]
[styles.accent]
foreground = "green"

[styles.accent-secondary]
modes = ["faint"]

[styles.debug]
foreground = "bright-magenta"

[styles.info]
foreground = "cyan"

[styles.warning]
foreground = "yellow"

[styles.error]
foreground = "bright-red"

#
# Elements define specific styles for different log elements.
#
[elements]
[elements.number]
foreground = "bright-blue"

[elements.boolean]
foreground = "yellow"

[elements.null]
foreground = "bright-red"

#
# Levels define styles for different log levels.
#
[levels]
[levels.warning.level]
style = "warning"
modes = ["reverse"]

[levels.warning.message]

[levels.error.time]
style = "error"

[levels.error.level]
style = "error"
modes = ["reverse"]

[levels.error.message]

#
# Indicators define styles for various status indicators.
#
[indicators]
[indicators.sync]
synced = { text = " " }
failed = { text = "!", inner.style = { foreground = "yellow", modes = ["bold"] } }
