[package]
name = "encstr"
version = "0.1.2"
edition.workspace = true
description = "Encoded string"
repository.workspace = true
license.workspace = true
workspace = "../.."

[dependencies]
memchr = "2"
