# Time format, see https://man7.org/linux/man-pages/man1/date.1.html for details.
time-format: '%b %d %T.%3N'

# Time zone name, see column "TZ database name" at
# https://en.wikipedia.org/wiki/List_of_tz_database_time_zones page.
time-zone: UTC

# Settings for fields processing.
fields:
  # Configuration of the predefined set of fields.
  predefined:
    time:
      names: [ts, TS, time, TIME, Time, _SOURCE_REALTIME_TIMESTAMP, __REALTIME_TIMESTAMP]
    logger:
      names: [logger, LOGGER, Logger]
    level:
      variants:
        - names: [level, LEVEL, Level]
          values:
            debug: [debug]
            info: [info, information]
            warning: [warning, warn]
            error: [error, err, fatal, critical, panic]
        - names: [PRIORITY]
          values:
            debug: [7]
            info: [6]
            warning: [5, 4]
            error: [3, 2, 1]
    message:
      names: [msg, message, MESSAGE, Message]
    caller:
      names: [caller, CALLER, Caller]
  # List of wildcard field names to ignore.
  ignore: ['_*']
  # List of exact field names to hide.
  hide: []

# Number of processing threads, configured automatically based on CPU count if not specified.
concurrency: ~

# Currently selected theme.
theme: one-dark-green

# A complete set of themes.
themes:
  one-dark-green:
    default:
      time:
        foreground: bright-black
      logger:
        foreground: bright-black
      caller:
        foreground: bright-black
        modes: [italic]
      level:
        foreground: bright-black
      delimiter:
        foreground: bright-black
      message:
        foreground: bright-white
      field-key:
        foreground: green
        modes: [underline]
      equal-sign:
        foreground: bright-black
      quote:
        foreground: cyan
      brace:
        foreground: bright-black
      ellipsis:
        foreground: bright-black
      at-sign:
        foreground: bright-black
        modes: [italic]
      'null':
        foreground: red
      boolean:
        foreground: red
      number:
        foreground: blue
      string:
        foreground: cyan
    levels:
      debug:
        level:
          foreground: magenta
      info:
        level:
          foreground: blue
      warning:
        time:
          foreground: yellow
        level:
          foreground: yellow
      error:
        time:
          foreground: red
          modes: [bold]
        level:
          foreground: red
        message:
          foreground: red
  one-dark-blue:
    default:
      time:
        foreground: bright-black
      logger:
        foreground: bright-black
      caller:
        foreground: bright-black
        modes: [italic]
      level:
        foreground: bright-black
      delimiter:
        foreground: bright-black
      message:
        foreground: bright-white
      field-key:
        foreground: blue
        modes: [underline]
      equal-sign:
        foreground: bright-black
      quote:
        foreground: cyan
      brace:
        foreground: bright-black
      ellipsis:
        foreground: bright-black
      at-sign:
        foreground: bright-black
        modes: [italic]
      'null':
        foreground: red
      boolean:
        foreground: red
      number:
        foreground: green
      string:
        foreground: cyan
    levels:
      debug:
        level:
          foreground: magenta
      info:
        level:
          foreground: blue
      warning:
        time:
          foreground: yellow
        level:
          foreground: yellow
      error:
        time:
          foreground: red
          modes: [bold]
        level:
          foreground: red
        message:
          foreground: red
  one-dark-green-truecolor:
    palette:
      - &red '#E06C75'
      - &gray '#636D83'
      - &white '#CFD7E5'
      - &blue '#61AFEF'
      - &yellow '#D19A66'
      - &cyan '#56B6C2'
      - &magenta '#C678DD'
      - &green '#98C379'
    default:
      time:
        foreground: *gray
      logger:
        foreground: *gray
      caller:
        foreground: *gray
        modes: [italic]
      level:
        foreground: *gray
      delimiter:
        foreground: *gray
      message:
        foreground: *white
      field-key:
        foreground: *green
        modes: [underline]
      equal-sign:
        foreground: *gray
      quote:
        foreground: *gray
      brace:
        foreground: *gray
      ellipsis:
        foreground: *gray
      at-sign:
        foreground: *gray
        modes: [italic]
      'null':
        foreground: *red
      boolean:
        foreground: *blue
      number:
        foreground: *blue
      string:
        foreground: *cyan
    levels:
      debug:
        level:
          foreground: *magenta
      info:
        level:
          foreground: *blue
      warning:
        time:
          foreground: *yellow
        level:
          foreground: *yellow
      error:
        time:
          foreground: *red
        level:
          foreground: *red
        message:
          foreground: *red
  one-dark-blue-truecolor:
    palette:
      - &red '#E06C75'
      - &gray '#636D83'
      - &white '#CFD7E5'
      - &blue '#61AFEF'
      - &yellow '#D19A66'
      - &cyan '#56B6C2'
      - &magenta '#C678DD'
      - &green '#98C379'
    default:
      time:
        foreground: *gray
      logger:
        foreground: *gray
      caller:
        foreground: *gray
        modes: [italic]
      level:
        foreground: *gray
      delimiter:
        foreground: *gray
      message:
        foreground: *white
      field-key:
        foreground: *blue
        modes: [underline]
      equal-sign:
        foreground: *gray
      quote:
        foreground: *gray
      brace:
        foreground: *gray
      ellipsis:
        foreground: *gray
      at-sign:
        foreground: *gray
        modes: [italic]
      'null':
        foreground: *red
      boolean:
        foreground: *red
      number:
        foreground: *green
      string:
        foreground: *cyan
    levels:
      debug:
        level:
          foreground: *magenta
      info:
        level:
          foreground: *blue
      warning:
        time:
          foreground: *yellow
        level:
          foreground: *yellow
      error:
        time:
          foreground: *red
        level:
          foreground: *red
        message:
          foreground: *red
  classic:
    default:
      time:
        foreground: bright-black
      logger:
        foreground: bright-black
      caller:
        foreground: bright-black
      level:
        foreground: magenta
      message:
        foreground: bright-white
      field-key:
        foreground: green
      equal-sign:
        foreground: bright-black
      ellipsis:
        foreground: bright-black
      at-sign:
        foreground: bright-black
      'null':
        foreground: yellow
      boolean:
        foreground: yellow
      number:
        foreground: cyan
    levels:
      debug:
        level:
          foreground: magenta
      info:
        level:
          foreground: cyan
      warning:
        level:
          foreground: bright-yellow
          modes: [reverse]
      error:
        level:
          foreground: bright-red
          modes: [reverse]
  classic-light:
    default:
      time:
        foreground: bright-black
      logger:
        foreground: bright-black
      caller:
        foreground: bright-black
      level:
        foreground: magenta
      message:
        foreground: black
      field-key:
        foreground: green
      equal-sign:
        foreground: bright-black
      ellipsis:
        foreground: bright-black
      at-sign:
        foreground: bright-black
      'null':
        foreground: yellow
      boolean:
        foreground: yellow
      number:
        foreground: cyan
    levels:
      debug:
        level:
          foreground: magenta
      info:
        level:
          foreground: cyan
      warning:
        level:
          foreground: bright-yellow
          modes: [reverse]
      error:
        level:
          foreground: bright-red
          modes: [reverse]
  retrograde:
    default:
      time:
        foreground: bright-black
      logger:
        foreground: bright-black
      caller:
        foreground: bright-black
      message:
        foreground: bright-white
      field-key:
        foreground: green
      equal-sign:
        foreground: bright-black
      ellipsis:
        foreground: bright-black
      at-sign:
        foreground: bright-black
      'null':
        foreground: yellow
      boolean:
        foreground: yellow
      number:
        foreground: cyan
    levels:
      debug:
        level:
          foreground: magenta
      info:
        level:
          foreground: cyan
      warning:
        level:
          foreground: bright-yellow
          modes: [reverse]
        delimiter:
          foreground: bright-yellow
          modes: [reverse]
        field-key:
          foreground: yellow
      error:
        level:
          foreground: bright-red
          modes: [reverse]
        delimiter:
          foreground: bright-red
          modes: [reverse]
        field-key:
          foreground: bright-red
  lsd:
    default:
      time:
        foreground: bright-black
      logger:
        foreground: bright-black
      caller:
        foreground: bright-black
        modes: [italic]
      level:
        foreground: magenta
      message:
        foreground: bright-white
      field-key:
        foreground: bright-blue
        modes: [underline]
      equal-sign:
        foreground: bright-black
      ellipsis:
        foreground: bright-black
      at-sign:
        foreground: bright-black
        modes: [italic]
      'null':
        foreground: yellow
      boolean:
        foreground: yellow
      number:
        foreground: yellow
      string:
        foreground: green
    levels:
      debug:
        level:
          foreground: magenta
      info:
        level:
          foreground: cyan
      warning:
        time:
          foreground: yellow
        level:
          foreground: bright-yellow
          modes: [bold]
      error:
        time:
          foreground: red
        level:
          foreground: bright-red
          modes: [bold]
  dmt:
    default:
      time:
        foreground: 8
      logger:
        foreground: 8
      caller:
        foreground: 8
        modes: [italic]
      level:
        foreground: 25
      message:
        foreground: 255
      field-key:
        foreground: 117
        modes: [underline]
      equal-sign:
        foreground: 8
      quote:
        foreground: 246
      brace:
        foreground: 246
      ellipsis:
        foreground: 8
      at-sign:
        foreground: 8
        modes: [italic]
      'null':
        foreground: 136
      boolean:
        foreground: 178
      number:
        foreground: 41
      string:
        foreground: 36
    levels:
      debug:
        level:
          foreground: 26
      info:
        level:
          foreground: 32
      warning:
        time:
          foreground: 192
        level:
          foreground: 192
        string:
          foreground: 108
        message:
          foreground: 192
      error:
        time:
          foreground: 214
        level:
          foreground: 214
        string:
          foreground: 214
        message:
          foreground: 214
