# Settings for fields processing.
fields:
  # Configuration of the predefined set of fields.
  predefined:
    time:
      names: ['@timestamp']
    logger:
      names: [log.logger]
    level:
      variants:
        - names: [log.level]
          values:
            debug: [debug, dbg, d]
            info: [info, inf, i, informational]
            warning: [warning, warn, wrn, w]
            error: [error, err, fatal, critical, panic, e]
    message:
      names: [message]
    caller:
      names: []
    caller-file:
      names: [log.origin.file.name]
    caller-line:
      names: [log.origin.file.line]
  # List of wildcard field names to ignore.
  ignore: ['_*']
  # List of exact field names to hide.
  hide:
    - log
